server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.1
  maxMoney: 9999
  description: Minimal money is ${limit.minMoney} dollar. Maximal money is ${limit.maxMoney}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Wts950718!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

